--[[
Action：行为
Condition：条件
Composites：
1.Sequencer:[队列节点]
类似于"and"，从左到右执行节点，当遇到子节点返回成功时，继续执行；
当遇到子节点返回失败时，返回失败，不再继续执行。  
2.Selector：[选择节点]
类似于"or"，从左到右执行节点，当遇到子节点返回失败时，继续执行；
当遇到子节点返回成功时，返回成功，不再继续执行。  
3.Parallel：[并行节点]
不同之处在于Parallel同时运行所有子节点，而Sequence是一个个从左到右运行的。
Decorators:
Conditional
Repeat
TimeOut
filter
]]
